Testing loops
Close ... the last attempt resulted in following error:
undefined method `ip' for "apache7":String

So it looks like all we need is instance[0]